### ISSUE TITLE
Does this TimeMixer support multiple input single output prediction?

### ISSUE THREAD

**Issue by zmce2018** [kwuking/TimeMixer#25]
Thank you for providing such great work. Does this TimeMixer support multiple input single output prediction? MISO is more practical since we were trying to use many covariate (Exogenous) time series to predict the target time series. 

I am also looking forward to seeing the code for TimeXer: Empowering Transformers for Time Series Forecasting with Exogenous Variables.

**Comment by kwuking** [comment]
Hi, without a doubt, MISO is indeed a very important issue. Currently, TimeMixer does not support MISO, but we are working hard to develop a new version to address this problem. Once we achieve results, we will release them as soon as possible and share them with the community. In the meantime, you can refer to our TimeXer work for this issue. Once again, thank you for your attention to our work.

**Comment by kwuking** [comment]
Hi, it is necessary to explain that channel_independence=1 means channel independence is enabled, where different channels' time series are treated independently. channel_independence=0 means channel independence is disabled. Using the method you mentioned can partially achieve the MISO effect, but due to the channel independence strategy, it does not actually use information from other channels for prediction.
