### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by lxs211** [kwuking/TimeMixer#89]
Hello, may I ask if I directly use the script sh file in the source code to reproduce the result and the original paper is a little different
![PixPin_2024-11-04_17-42-56](https://github.com/user-attachments/assets/8aea822f-b89c-429f-8339-d1b7dfa26778)
Results from the original paper
![PixPin_2024-11-04_17-45-11](https://github.com/user-attachments/assets/921e1941-d478-4b2c-b970-9530422d5b49)

**Comment by kwuking** [comment]
Many thank for your interest in our work. Due to the inherent stochastic nature of deep learning, variations in execution environments, and discrepancies in software versions, achieving completely consistent results across different devices and settings is indeed quite challenging. We have also reported the error margins in the appendix for your reference.
