### ISSUE TITLE
Why does it look terrible in results? (Weather dataset)

### ISSUE THREAD

**Issue by lzmax888** [kwuking/TimeMixer#9]
[40.pdf](https://github.com/kwuking/TimeMixer/files/14951922/40.pdf)
[60.pdf](https://github.com/kwuking/TimeMixer/files/14951924/60.pdf)
[60.pdf](https://github.com/kwuking/TimeMixer/files/14951925/60.pdf)
[80.pdf](https://github.com/kwuking/TimeMixer/files/14951926/80.pdf)
![image](https://github.com/kwuking/TimeMixer/assets/55983394/ad7e940c-ad84-4aa9-8a2f-fd7bd723e50d)

It seems it learned nothing.

**Comment by kwuking** [comment]
Hi, I just responded to your query regarding the training failure. It seems that the issue is due to the training not being successful. You may refer to the previous [issue](https://github.com/kwuking/TimeMixer/issues/8) for more information. Additionally, it is well known that the weather dataset is indeed very challenging to predict due to its lack of regular patterns and the presence of significant noise, all of which greatly complicate the forecasting. You can start by setting up the corresponding environment according to the requirements to achieve successful training.
